from bs4 import BeautifulSoup

from crawler import SkinCeuticalsCrawler
from models import RawCrawledProduct


def load_html(file_path) -> BeautifulSoup:
    with open(file_path, "r") as f:
        return BeautifulSoup(f.read(), "html.parser")


def test_get_product_urls_empty_page_returns_empty_list():
    crawler = SkinCeuticalsCrawler()
    soup = BeautifulSoup("", "html.parser")
    res = crawler._get_product_urls(soup)
    assert res == []


def test_get_product_urls_returns_list_of_product_urls():
    crawler = SkinCeuticalsCrawler()
    soup = load_html("tests/data/products_short.html")
    res = crawler._get_product_urls(soup)
    assert len(res) == 13
    expected_urls = [
        "https://www.skinceuticals.com/skincare/vitamin-c-serums/c-e-ferulic-with-15-l-ascorbic-acid/S17.html",
        "https://www.skinceuticals.com/skincare/anti-aging-creams/triple-lipid-restore-2-4-2/S09.html",
        "https://www.skinceuticals.com/skincare/anti-aging-serum/p-tiox-anti-wrinkle-serum/S123.html",
        "https://www.skinceuticals.com/skincare/skincare-sets/best-sellers-discovery-set/S109.html",
        "https://www.skinceuticals.com/skincare/anti-aging-creams/a.g.e.-advanced-eye-for-dark-circles/S119.html",
        "https://www.skinceuticals.com/skincare/hydrating-serums/hydrating-b5-gel/S39.html",
        "https://www.skinceuticals.com/skincare/anti-aging-creams/a.g.e.-interrupter-advanced/S117.html",
        "https://www.skinceuticals.com/skincare/vitamin-c-serums/phloretin-cf-with-ferulic-acid/S52.html",
        "https://www.skinceuticals.com/skincare/anti-aging-serum/a.g.e.-interrupter-ultra-serum/S125.html",
        "https://www.skinceuticals.com/skincare/vitamin-c-serums/c-e-ferulic-with-15-l-ascorbic-acid/S17.html",
        "https://www.skinceuticals.com/skincare/anti-aging-serum/p-tiox-anti-wrinkle-serum/S123.html",
        "https://www.skinceuticals.com/skincare/anti-aging-creams/triple-lipid-restore-2-4-2/S09.html",
        "https://www.skinceuticals.com/skincare/skincare-sets/best-sellers-discovery-set/S109.html",
    ]
    assert set(res) == set(expected_urls)


def test_collect_product_details_from_soup():
    crawler = SkinCeuticalsCrawler()
    soup = load_html("tests/data/product.html")
    product_url = "some_product_url"
    res = crawler._collect_product_details_from_soup(soup, product_url)
    assert isinstance(res, RawCrawledProduct)
    assert res.name == "C E Ferulic® with 15% L-Ascorbic Acid"
    assert res.url == product_url
    assert res.current_price == 185.0
    assert res.category == ["SERUMS", "Vitamin C Serums"]
    assert (
        res.short_description
        == "The #1 dermatologist recommended vitamin C serum among medical aesthetic skincare brands, this dayti"
    )
    assert (
        res.description
        == "The #1 dermatologist recommended vitamin C serum among medical aesthetic skincare brands, this daytime vitamin C serum for the face that delivers advanced environmental protection and clinically improves the 8 signs of aging, including the appearance of fine lines and wrinkles, discoloration, loss of firmness, and brightness on all skin tones. Clinically proven to reduce up to 48% of potential damage from free radicals formed by pollution, the sun, and metals for up to 8x stronger skin against environmental aggressors. C E Ferulic ®vitamin C serum features a synergistic antioxidant combination of 15% pure vitamin C (L-ascorbic acid), 1% vitamin E (alpha tocopherol), and 0.5% ferulic acid to enhance protection against environmental damage caused by free radicals that can contribute to visible signs of atmospheric aging. C E Ferulic ®is now clinically demonstrated to reduce combined oxidative damage generated by UVA/UVB rays, ozone pollution, and diesel engine exhaust by up to 41%. In addition to antioxidant protective benefits, this ferulic acid serum brightens overall complexion while visibly improving effects from photodamage and eight different signs of aging, such as loss of firmness and the appearance of fine lines and wrinkles.C E Ferulic ®vitamin C serum features a synergistic antioxidant combination of 15% pure vitamin C (L-ascorbic acid), 1% vitamin E (alpha tocopherol), and 0.5% ferulic acid to enhance protection against environmental damage caused by free radicals that can contribute to visible signs of atmospheric aging. C E Ferulic ®is now clinically demonstrated to reduce combined oxidative damage generated by UVA/UVB rays, ozone pollution, and diesel engine exhaust by up to 41%. In addition to antioxidant protective benefits, this ferulic acid serum brightens overall complexion while visibly improving effects from photodamage and eight different signs of aging, such as loss of firmness and the appearance of fine lines and wrinkles.C E Ferulic ®"
    )
    assert res.meta_description == ""
    assert res.purchase_requirements == ""
    expected_image_urls = [
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dwd20af22a/Products/S17/SKC_CEF_Allure_Packshot.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-skinc-us-Library/default/dwab25bada/images/pdp/SKC_HOW_TO_GLOBAL_US_DR_CEF.jpg?sw=68&sh=68&sm=cut&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dwd732337c/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_02_TEXTURE.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw9ad58798/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_03_INGREDIENTS.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dwde57a861/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_04_PRO_FORMULA.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw03c71e10/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_05_CUSTOMER_REVIEW.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw50132fcc/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_06_PHYSICIAN%20INSIGHT.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dweb76087b/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_07_HOW_TO_APPLY_V2.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw04b59022/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_08_PRODUCT_COMPARISON.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw840d64f7/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_09_PRODUCT_COMPARISON.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw84ef65c0/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_10_ON_MODEL_V5.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw1259aa0e/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_11_AM_ROUTINE.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw4894de44/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_11_RESILTS.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw29fac946/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_12_BEFORE_+_AFTER.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw41fcaec1/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_13.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
        "https://www.skinceuticals.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-acd-skinceuticals-master-catalog/default/dw279d25e0/pdpimages/CE-FERULIC/CEF_2025_PDP_ALT_14.jpg?sw=68&sh=68&sm=cut&sfrm=jpg&q=70",
    ]
    image_urls = [image.data for image in res.images]
    assert len(image_urls) == len(expected_image_urls)
    assert set(image_urls) == set(expected_image_urls)
    assert res.attributes == ""
    assert res.uom == ["30 ml"]
    assert res.documents == []
